-- spec-003: machine registry, tags, and the Envers audit foundation.
-- H2 dialect. `machine` is the first @Audited entity, so this migration also
-- hand-creates the Envers `revinfo` revision table and `machine_aud` (ddl-auto
-- is none, so every _aud table is created here beside its base table). `app_user`
-- already exists from V2 (spec-011).

-- Envers revision table, backed by audit/AuditRevision. Each audited write opens
-- one row, stamped with the ambient actor (user_id nullable; via UI/MCP/SYSTEM).
CREATE TABLE revinfo (
    rev       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    timestamp BIGINT       NOT NULL,
    user_id   VARCHAR(36),
    via       VARCHAR(20),
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE machine (
    id              VARCHAR(36)  NOT NULL,
    owner_id        VARCHAR(36)  NOT NULL,
    host            VARCHAR(255) NOT NULL,
    port            INTEGER      NOT NULL,
    login_user      VARCHAR(255) NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    pinned_host_key VARCHAR(1024),
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    CONSTRAINT pk_machine PRIMARY KEY (id),
    CONSTRAINT uq_machine_owner_host_port_user UNIQUE (owner_id, host, port, login_user),
    CONSTRAINT fk_machine_owner FOREIGN KEY (owner_id) REFERENCES app_user (id)
);

CREATE INDEX idx_machine_owner ON machine (owner_id);

CREATE TABLE tag (
    id       VARCHAR(36)  NOT NULL,
    owner_id VARCHAR(36)  NOT NULL,
    name     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id),
    CONSTRAINT uq_tag_owner_name UNIQUE (owner_id, name),
    CONSTRAINT fk_tag_owner FOREIGN KEY (owner_id) REFERENCES app_user (id)
);

CREATE TABLE machine_tag (
    machine_id VARCHAR(36) NOT NULL,
    tag_id     VARCHAR(36) NOT NULL,
    CONSTRAINT pk_machine_tag PRIMARY KEY (machine_id, tag_id),
    CONSTRAINT fk_machine_tag_machine FOREIGN KEY (machine_id) REFERENCES machine (id),
    CONSTRAINT fk_machine_tag_tag FOREIGN KEY (tag_id) REFERENCES tag (id)
);

-- Audit table for `machine`. Envers runs the validity audit strategy (ARCH.md),
-- so besides `rev`/`revtype` each row carries `revend`: the revision at which
-- this version stopped being current (NULL while current). Envers back-fills it
-- when the next revision of the same row lands. `tag` membership is @NotAudited
-- (no machine_tag_aud); owner_id is stored with its target un-audited.
CREATE TABLE machine_aud (
    id              VARCHAR(36) NOT NULL,
    rev             BIGINT      NOT NULL,
    revend          BIGINT,
    revtype         TINYINT,
    owner_id        VARCHAR(36),
    host            VARCHAR(255),
    port            INTEGER,
    login_user      VARCHAR(255),
    status          VARCHAR(20),
    pinned_host_key VARCHAR(1024),
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT pk_machine_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_machine_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev),
    CONSTRAINT fk_machine_aud_revend FOREIGN KEY (revend) REFERENCES revinfo (rev)
);
